name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Extract version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version $VERSION"
        
    - name: Update version in Info.plist
      run: |
        # Update version in both Info.plist files
        /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${{ steps.get_version.outputs.VERSION }}" ClaudeNavigator/Info.plist
        /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${{ steps.get_version.outputs.VERSION }}" ClaudeNavigator.app/Contents/Info.plist
        
        # Increment build number
        CURRENT_BUILD=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" ClaudeNavigator/Info.plist)
        NEW_BUILD=$((CURRENT_BUILD + 1))
        /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" ClaudeNavigator/Info.plist
        /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" ClaudeNavigator.app/Contents/Info.plist
        
    - name: Build app
      run: |
        ./build.sh
        
    - name: Install create-dmg
      run: |
        brew install create-dmg
        
    - name: Update DMG scripts with version
      run: |
        # Update version in DMG creation scripts
        sed -i '' "s/VERSION=\"[0-9.]*\"/VERSION=\"${{ steps.get_version.outputs.VERSION }}\"/" create-dmg-simple.sh
        
    - name: Create DMG installer
      run: |
        ./create-dmg-simple.sh
        
    - name: Create ZIP archive
      run: |
        zip -r "ClaudeNavigator-${{ steps.get_version.outputs.VERSION }}.zip" ClaudeNavigator.app
        
    - name: Generate release notes
      id: release_notes
      run: |
        # Extract release notes from CHANGELOG.md for this version
        echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
        awk '/^## \[?${{ steps.get_version.outputs.VERSION }}\]?/{flag=1;next}/^## /{flag=0}flag' CHANGELOG.md >> $GITHUB_OUTPUT || echo "See CHANGELOG.md for details" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## 🎉 Claude Terminal Navigator v${{ steps.get_version.outputs.VERSION }}
          
          ${{ steps.release_notes.outputs.RELEASE_NOTES }}
          
          ### 📦 Installation
          
          #### Option 1: DMG Installer (Recommended)
          1. Download `Claude-Terminal-Navigator-Installer-${{ steps.get_version.outputs.VERSION }}.dmg`
          2. Double-click to mount
          3. Drag ClaudeNavigator to Applications
          4. Launch from Applications
          
          #### Option 2: ZIP Archive
          1. Download `ClaudeNavigator-${{ steps.get_version.outputs.VERSION }}.zip`
          2. Extract and move to Applications
          
          ---
          *Built with GitHub Actions*
        files: |
          Claude-Terminal-Navigator-Installer-${{ steps.get_version.outputs.VERSION }}.dmg
          ClaudeNavigator-${{ steps.get_version.outputs.VERSION }}.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}