name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.9"
    
    - name: Check Swift version
      run: swift --version
      
    - name: Check Swift syntax
      run: swift package describe
    
    - name: Build Debug
      run: swift build -c debug
        
    - name: Build Release
      run: swift build -c release
    
    - name: Verify build output
      run: |
        test -f .build/release/ClaudeNavigator
        echo "✅ Release binary exists"
        
    - name: Check Info.plist
      run: |
        test -f ClaudeNavigator/Info.plist
        /usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" ClaudeNavigator/Info.plist
        /usr/libexec/PlistBuddy -c "Print :CFBundleName" ClaudeNavigator/Info.plist
        echo "✅ Info.plist is valid"
    
    - name: Test App Bundle Creation
      run: |
        mkdir -p "ClaudeNavigator.app/Contents/MacOS"
        cp .build/release/ClaudeNavigator "ClaudeNavigator.app/Contents/MacOS/"
        cp ClaudeNavigator/Info.plist "ClaudeNavigator.app/Contents/"
        
        # Verify bundle structure
        test -f "ClaudeNavigator.app/Contents/MacOS/ClaudeNavigator"
        test -f "ClaudeNavigator.app/Contents/Info.plist"
        echo "✅ App bundle created successfully"
        
    - name: Security scan
      run: |
        # Check for hardcoded secrets
        if grep -r "password\|secret\|key\|token" ClaudeNavigator/*.swift | grep -v "// " | grep -i "="; then
          echo "❌ Potential hardcoded secrets found!"
          exit 1
        else
          echo "✅ No hardcoded secrets detected"
        fi